###
POST http://localhost:8000/api/feedbacks
Content-Type: application/json

{

    "user_id":3,
    "session_id":4,
    "rating":8,
    "comments":"the session was nice"

}
###
PUT http://localhost:8000/api/feedbacks/3
Content-Type: application/json

{

     "rating":5
}
###

DELETE http://localhost:8000/api/feedbacks/3
