###
POST http://localhost:8000/api/resources
Content-Type: application/json

{

    "title":"Depression",
    "content":"Depression is a mood disorder that causes a persistent feeling of sadness and loss of interest. Also called major depressive disorder or clinical depression, it affects how you feel, think and behave and can lead to a variety of emotional and physical problems. You may have trouble doing normal day-to-day activities, and sometimes you may feel as if life isn't worth living."

}
###
PUT http://localhost:8000/api/resources/1
Content-Type: application/json

{

     "title":"PTSD"
}
###

DELETE http://localhost:8000/api/resources/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiZnVsbF9uYW1lIjoiQ2hyaXN0aW5lIFJpYW4gIiwiY29udGFjdF9waG9uZSI6IjA3OTkwODcxODgiLCJhZGRyZXNzIjoiNzAga3V0dXMiLCJpZCI6MX0sInJvbGUiOiJhZG1pbiIsImV4cCI6MTczODE2NTQ0NX0.OYB-jpwj6PAabV6osCMDkE3st8YTUosfKYijpzHEKMA