
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

  "full_name": "Christine Rian ",
  "email": "riyan99@gmail.com",
  "contact_phone": "0799087188",
  "address": "90 kenya",
  "role": "admin",
  "password": "2003"
}
###
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

  "full_name": "stine Rian ",
  "email": "rian99@gmail.com",
  "contact_phone": "0799987188",
  "address": "490 kenya",
  "role": "therapist",
  "password": "2903"
}
###
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

   "full_name": "John Doe",
   "email": "john@gmail.com",
   "contact_phone": "+1-123-456-7890",
   "address": "123 Main St, New York, NY 10001",
   "role": "user",
  "password": "2093"
}
###
POST    http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "rian99@gmail.com",
    "password": "2903"
  }

###
POST    http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "riyan99@gmail.com",
    "password": "2003"
  }
###
POST http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "john@gmail.com",
    "password": "2093"
  }

